name: rsvp_server
description: Shelf-based Dart Server
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  shelf_static: ^1.1.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite3: ^2.4.2
  crypto: ^3.0.3
